---
sandbox: true
tenant_namespace: "{{ meta.namespace }}"
migration_ui: true
migration_controller: true
cluster_name: host
operator_namespace: "{{ lookup('env', 'OPERATOR_NAMESPACE') | default('openshift-migration') }}"
azure_resource_group: ""
configmap_secret: ""
controller_state: absent
deprecated_cors_configuration: false
cors_origins: []
proxy_secret_name: "migration-proxy"
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
image_pull_policy: Always
mig_controller_image: "{{ registry }}/{{ project }}/{{ mig_controller_repo }}"
mig_controller_limits_cpu: "100m"
mig_controller_limits_memory: "800Mi"
mig_controller_repo: "{{ lookup( 'env', 'MIG_CONTROLLER_REPO') }}"
mig_controller_requests_cpu: "100m"
mig_controller_requests_memory: "350Mi"
mig_controller_version: "{{ snapshot_tag | default(lookup( 'env', 'MIG_CONTROLLER_TAG')) }}"
mig_controller_image_fqin: "{{ mig_controller_image }}:{{ mig_controller_version }}"
discovery_volume_path: "/var/cache/discovery"
mig_pv_limit: "100"
mig_pod_limit: "100"
mig_namespace_limit: "10"
mig_ui_cluster_api_endpoint: ""
mig_ui_configmap_data: ""
mig_ui_configmap_name: mig-ui-config
mig_ui_config_namespace: openshift-migration
mig_ui_image: "{{ registry }}/{{ project }}/{{ mig_ui_repo }}"
mig_ui_oauth_user_scope: "user:full"
mig_ui_oauth_redirect_url: ""
mig_ui_oauth_secret: ""
mig_ui_repo: "{{ lookup( 'env', 'MIG_UI_REPO') }}"
mig_ui_version: "{{ snapshot_tag | default(lookup( 'env', 'MIG_UI_TAG')) }}"
mig_ui_image_fqin: "{{ mig_ui_image }}:{{ mig_ui_version }}"
migration_registry_image: "{{ registry }}/{{ project }}/{{ migration_registry_repo }}"
migration_registry_repo: "{{ lookup( 'env', 'MIGRATION_REGISTRY_REPO') }}"
migration_registry_version: "{{ lookup( 'env', 'MIGRATION_REGISTRY_TAG') }}"
migration_registry_image_fqin: "{{ migration_registry_image }}:{{ migration_registry_version }}"
olm_managed: false
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_timeout: 1h
ui_state: absent
